version = "2.7.4"
style = defaultWithAlign

docstrings                 = JavaDoc
maxColumn                  = 100
rewrite.rules              = [RedundantBraces, SortImports, SortModifiers, PreferCurlyFors]
#rewrite.rules             = [RedundantBraces, RedundantParens, SortImports]
# spaces.inImportCurlyBraces = true
indentOperator             = spray
unindentTopLevelOperators  = true
align.preset               = more
align.stripMargin          = true
align.openParenDefnSite    = true
align.openParenCallSite    = true
align.arrowEnumeratorGenerator = true
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
danglingParentheses.ctrlSite = true
newlines.topLevelStatements = [before,after]
newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.beforeCurlyLambdaParams = always
newlines.afterCurlyLambdaParams = never
newlines.implicitParamListModifierPrefer = before
newlines.avoidForSimpleOverflow = [punct]
newlines.avoidInResultType = true
